parameters:

services:

    _defaults:
        autowire: true
        autoconfigure: true


    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    App\Api\Action\:
        resource: '../src/Api/Action'
        tags: ['controller.service_arguments']


    App\Api\Listenner\JsonExceptionResponseTransformerListener:
        tags:
            -{ name:kernel.event_listener, event:kernel.exception, method:onKernelException, priority: 100 }



